# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              otp: 25
              elixir: 1.14
          - pair:
              otp: 27
              elixir: 1.18
    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir OTP ${{ matrix.pair.otp }} / Elixir ${{ matrix.pair.elixir }}
      uses: erlef/setup-elixir@v1
      with: 
        otp-version: ${{ matrix.pair.otp }}
        elixir-version: ${{ matrix.pair.elixir }}
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-${{ matrix.pair.otp }}-${{ matrix.pair.elixir }}
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
